language: generic

deploy:
  provider: s3
  access_key_id:
    secure: "bVeaBmGBHs8cPiwTjRKJt7NC51PznKP31xpRaUP6vCn5qu6EKNGLBCOqpnI0871GOwVC3MTLuhwuKnTnCRspo/OOgt3ddNouJUKAC0AQ8nSh59tWA1OpwES9bOv4jE1AFluFxQwIPTEI5+f1PSFOjiG3FYhnTPvW4cNlk5hHERwihBbPdaiOjRd8QCn4THVQLIDD6HnsZyaeiNNycNfffZOqPXVPfU1uzgvK0j8IQsj/JM7DdgxzN1ivFWekELlNYlanzw6u/iUXIQ4L+iSBNAF1pSyrDD9Yw62L8pe/Z6f6tU8hPkyPnUszIjgXV60s4SbFe9/RunXV/dp5ixsFIEKIGTRuMboNuBJXea0ZM+A7z/8RZfkN2wh+ujMUUZTYyCoEBrhAxPTuBWM/wG0Jbs0c4Kvvb0fpmKLjSfnNMB8JCDfQ7q4P0vlMTRGCUKNGqXCKD/aol83lJLcHwykUTI5ua0F/pXEV/UWQJ+Ox7O23i84dsJTa3u4W5kWHu59VEiFFT9vr8n6aN3cl96CzTROb0tMtfY9BQF7n6A4VyKq12P0g4dgwhVwJ0JcYRdItREKE6c/3NSEwFDQt5W6sHsCbG/o9vrA7fZKDMvd5cME8VDMnMcv6Ddye2B2ciASgbrdJJbYIbC/LWs3vo54OC/Ib33RBwRwfAs0v2rONaZQ="
  secret_access_key:
    secure: "F0/2k3Jzl/s2v7rYADfF2GguL5q9zKJgFsGAK889jtW58OkoaL+JPzj94jKXflyoo3Hllhkky8ibuKqTrUN+Q3KO0DP3OuwrAo2ZKMNKr8n5w+KyrRA57+LhEJDN9dQxJNZaQL9h/LGTNnxcnsLMX0aW8hggB5j8paaDRHAj7AhB/YXiwsk+VjJa+V1c8qlcKarqBm816IgHMepDIOrzLz9FBZDBekyj2GWBWDt1gjS3lRsn5sJtg909WqRJzF3YWaUx4/F515bW1GwAlxZtfYUx3NACkHqQxHFGC7qcLe4pPSIoXvOMUrdXIKRMbLUpqZ0lFW2m81RSR3t0vsBtne+DSiB2z0uYjO+DhOVDXUdanaafPJFaOsv8LWh+Eybj92ThmSNGrfgiyUWdTpk7GSsUdJfnW/2WGaygYPhexE4whRQ1vcwubyZqIlhBi+bL+2vXsDQ8sLUCadOFN0OfNssHrWb0FjV1pMbhHYdS2Wgy8u1CIp712ErvCUzGOnEEPagxth+OmiLeo+xuNYGBLHhS/CErOd5tHJZSduR5G2Cl4HHkoIqPoNRAdT1LwFV6QpEGEc2H2ySJ1zzA9F0hTTCkQ43mh8oLM1zkcrg8/XJKxRDFByBrNfnetxJ3buHRUysOrffXBLfCSsRn6PQDkyx0Fd6l9uE1ofdsZKJrgGI="
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: www/
  upload_dir: projects/last-known-mouse-position/
